### PR TITLE
Cargo clippy --fix

### PR DESCRIPTION
**Pull request by Snowiiii**

### CODE REVIEW

**Review by macmv — CHANGES_REQUESTED** [review]
ok as a quick first pass:
- use the formatter. `cargo fmt` will reformat the whole project. it needs nightly to be enabled.
- limit each PR to one change. These refactors are mostly good, but the `Cargo.lock` update should be its own PR.
- include a description of the PR. what does this change? why should I merge this? etc etc

I appriciate the change, and again this looks like some great cleanup. It just needs to follow the formatting conventions and in general version bumps (changing Cargo.lock) should be their own PR.

**Comment by Snowiiii** [comment]
Oki

**Comment by Snowiiii** [comment]
@macmv is this Okay now ?

**Review by Snowiiii — COMMENTED** [review]
.

**Review by macmv — APPROVED** [review]
in the future, can you write something instead of just commenting with a `.`? it's not very useful to just put a dot in a comment. thanks for the changes, it definitely helps clean things up.

**Pull request merged**
